### ISSUE TITLE
Failed authentication with /xxx (Unexpected Kafka request of type PRODUCE during SASL handshake.)

### ISSUE THREAD

**Issue by wuare** [doujiang24/lua-resty-kafka#118]
各位：
有没人使用的时候遇到这种报错，使用sasl认证
Kafka服务端报错
Failed authentication with /xxx (Unexpected Kafka request of type PRODUCE during SASL handshake.)

lua-resty-kafka报错
producer.lua:271: buffered messages send to kafka err: closed, retryable: true, topic: test, partition_id: 0, length: 2, context: ngx.timer, client: xxx, server: 0.0.0.0:9080

我运行了很多次，只有1-2次是正常发送消息，大部分情况都在报这个错

kafka版本：2.6.1
lua-resty-kafka版本：master

**Comment by biubiue** [comment]
I reslove this problem, please see  [lua-resty-kafka](https://github.com/biubiue/lua-resty-kafka)
