### ISSUE TITLE
SASL module failed on specific partitions

### ISSUE THREAD

**Issue by salon0630** [doujiang24/lua-resty-kafka#122]
Hi, thanks for providing lua-resty-kafka module, which is great module for us sending message from our Openresty to Kafka.
Recently, there's a need for us to use Kafka Quota functions, we thought it'd better used along with SASL enabled.
We downloaded lua-resty-kafka master branch and having some tests, but weird things happened: the SASL work, yet somehow some of the partitions failed to send messages.
E.g. we have 3 partitions, while partition 0 will fail, but partition 1, 2 success. we try to extend the partitions to 9, then we have 0, 3, 6 failed, while other partitions success.

Also we've use `kcat` command with SASL enabled on Kafka for A/B testing, which work flawlessly.
Attached is the error logs from Openresty, Kafka

lua resty kafka error log:
<img width="1680" alt="截圖 2022-03-14 下午4 14 23" src="https://user-images.githubusercontent.com/49525576/158132658-cf970a23-11b5-414c-ad0c-75ce54ac00b0.png">

Kafka error log:
<img width="1570" alt="截圖 2022-03-14 下午4 23 55" src="https://user-images.githubusercontent.com/49525576/158132975-2d2af534-e222-440d-8fc2-f0caff5cb017.png">

Please let us know what else information we have to provide, thanks for reading our problem and your works

**Comment by salon0630** [comment]
We found the reason which may cause the abnormally

the `client.lua` file 149, j=1, where Kafka brokers should start from index 0
that's why broker0 always failed

https://github.com/doujiang24/lua-resty-kafka/blob/73204492ceae8210b7dc22a3c34f04da8759ccdf/lib/resty/kafka/client.lua#L149


does this `j=1` has specific reason?

**Comment by doujiang24** [comment]
oh, I think it's a bug, we'd better use pairs here.
Could you please create a PR to fix it? Thanks.

**Comment by salon0630** [comment]
PR created.
https://github.com/doujiang24/lua-resty-kafka/pull/123
