### ISSUE TITLE
resty.kafka.producer send not timestamp supported?

### ISSUE THREAD

**Issue by zq-2020** [doujiang24/lua-resty-kafka#134]
Hello,
I produce messages by  require "resty.kafka.producer" send.
consumer use kafka-python.
consumer.offsets_for_times({topic_partition: timestamp})  return offset is always None.
But if send in other ways, offsets_for_times return correct offset.

**Comment by fireflyhoo** [comment]
chang  this code  

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/3061324/170446801-fc14c521-3498-4b92-88c8-cb2bded25f48.png">

to

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/3061324/170446910-c1222ed0-94e3-487b-be52-dad190f23b6b.png">


and  set  api_version   init 


<img width="959" alt="image" src="https://user-images.githubusercontent.com/3061324/170447027-c1d06c12-77d4-4227-9fba-546c8bf096a7.png">

**Comment by zq-2020** [comment]
@fireflyhoo 
Thanks!
