### ISSUE TITLE
can use log_by_lua_file send message to kafka0.9.0.2.3 ? nginx err.log 

### ISSUE THREAD

**Issue by yangchao228** [doujiang24/lua-resty-kafka#19]
if i use content_by_lua_file，send message to kafka0.9.0.2.3 is ok，but use log_by_lua_file meet err

**Comment by yangchao228** [comment]
2016/02/22 20:06:28 [error] 10239#0: *10913 open() "/openresty-test/html/yangchao" failed (2: No such file or directory), client: 10.46.27.172, server: , request: "GET /yangchao HTTP/1.0", host: "kafka1.bigdata.yiran.com:6699"
2016/02/22 20:06:28 [error] 10239#0: *10907 open() "/openresty-test/html/yangchao" failed (2: No such file or directory), client: 10.46.27.172, server: , request: "GET /yangchao HTTP/1.0", host: "kafka1.bigdata.yiran.com:6699"
2016/02/22 20:06:28 [error] 10239#0: *10905 open() "/openresty-test/html/yangchao" failed (2: No such file or directory), client: 10.46.27.172, server: , request: "GET /yangchao HTTP/1.0", host: "kafka1.bigdata.yiran.com:6699"
2016/02/22 20:06:28 [error] 10239#0: *10911 open() "/openresty-test/html/yangchao" failed (2: No such file or directory), client: 10.46.27.172, server: , request: "GET /yangchao HTTP/1.0", host: "kafka1.bigdata.yiran.com:6699"
2016/02/22 20:06:28 [error] 10239#0: *10910 open() "/openresty-test/html/yangchao" failed (2: No such file or directory), client: 10.46.27.172, server: , request: "GET /yangchao HTTP/1.0", host: "kafka1.bigdata.yiran.com:6699"
2016/02/22 20:06:28 [error] 10239#0: *10909 open() "/openresty-test/html/yangchao" failed (2: No such file or directory), client: 10.46.27.172, server: , request: "GET /yangchao HTTP/1.0", host: "kafka1.bigdata.yiran.com:6699"
2016/02/22 20:06:28 [error] 10239#0: *10908 open() "/openresty-test/html/yangchao" failed (2: No such file or directory), client: 10.46.27.172, server: , request: "GET /yangchao HTTP/1.0", host: "kafka1.bigdata.yiran.com:6699"
2016/02/22 20:06:28 [error] 10239#0: *10914 open() "/openresty-test/html/yangchao" failed (2: No such file or directory), client: 10.46.27.172, server: , request: "GET /yangchao HTTP/1.0", host: "kafka1.bigdata.yiran.com:6699"

**Comment by doujiang24** [comment]
@yangchao228 This may be you don't have specified the content phase handler and the nginx default handler shows this error.
You'd better show your nginx.conf.

**Comment by doujiang24** [comment]
consider reloved
