### ISSUE TITLE
 too many pending timers

### ISSUE THREAD

**Issue by chenyoufu** [doujiang24/lua-resty-kafka#22]
if I send fast, the error log:

[lua] producer.lua:280: _flush_buffer(): failed to create timer at _flush_buffer, err: too many pending timers.

But I use the ngx.timer.pending_count() and ngx.timer.running_count() function watching the  pending  and running value. The pending value max is 2 and the running value max is 1.

This is my nginx.conf setting:

lua_max_pending_timers 1024;
lua_max_running_timers 256;

Thanks!

**Comment by doujiang24** [comment]
@chenyoufu where did you add the pending_count ?
You can add the `pending_count` after the error_log, like
```lua
_flush_buffer = function (self)
    local ok, err = timer_at(0, _flush, self)
    if not ok then
        ngx_log(ERR, "failed to create timer at _flush_buffer, err: ", err)
        ngx_log(ERR, "pending:", ngx.timer.pending_count())
    end
end
```

**Comment by chenyoufu** [comment]
@doujiang24 I  get the pending timer from location timers every 1 second.
```
watch  curl 127.0.0.1:80/timers
```

``` 
worker_processes 1;
server {
        listen 80;
        location = / {
            lua_need_request_body on;
            content_by_lua_file es/kafka.lua;
        }
       location = /timers {
            content_by_lua_block{
                ngx.say(ngx.worker.id() .. ":" .. ngx.worker.pid() .. ":" .. ngx.timer.pending_count() .. ":" .. ngx.timer.running_count())
            }
        }
}
```

**Comment by chenyoufu** [comment]
@doujiang24 I add the pending_count after the error_log, It exceeding the 1024 limit, Thanks.
```
2016/04/14 09:13:13 [error] 2446#2446: *57 [lua] producer.lua:280: _flush_buffer(): failed to create timer at _flush_buffer, err: too many pending timers"
2016/04/14 09:13:13 [error] 2446#2446: *57 [lua] producer.lua:281: _flush_buffer(): pending:1024"
```

**Comment by doujiang24** [comment]
@chenyoufu There have a little time for a timer from pending to running.
Your situation is possible, and yes, we can do some optimize:
We can add `try _flush_lock` in `_flush_buffer`, if the try is failed, then we do not need to add a timer.
Would you try to complete a patch for this?

You mentioned the recursively callback is safe :)

**Comment by chenyoufu** [comment]
@doujiang24 Thanks, I will try the optimize.

**Comment by chenyoufu** [comment]
@doujiang24 I try to add try _flush_lock in _flush_buffer is useless. I find the real reason.
If a http request (Especially in the first request) send 1000 messages, the batch num is 200, then 800 timers is created, but only 5 is effective.
This is the sample code.
```
-- docs array length is 1000
for _, doc in ipairs(docs) do
      local msg = cjson.encode(doc)
      local ok, err = p:send(topic, nil, msg)
end
```
```
if not self.flushing and (ringbuffer:need_send() or is_exiting()) then
    _flush_buffer(self)
end
```
The if condition is always true when the looping count > 200, then 800 timers is created at this request.

**Comment by doujiang24** [comment]
@chenyoufu 
Sorry, I forgot I have added `try _flush_lock` in https://github.com/doujiang24/lua-resty-kafka/blob/master/lib/resty/kafka/producer.lua#L349.

May be we can try another way:  add another lock `flush_pending_lock`, but we should be careful to handle the lock release :)

**Comment by doujiang24** [comment]
We can create a timer when: 1. try `_flush_lock` true; or 2. `_flush_pending_lock` true.
We should release the `pending_lock` when: 1. enter function `_flush`; or 2. leaving function `_flush`.
Thoughts?

**Comment by chenyoufu** [comment]
I apply a method like this, add a timer_num property per producer, if the int(left_num / batch_num) > timer_num, then create a timer:
```
local function _need_timer(self)
    local ringbuffer = self.ringbuffer
    local left_num = ringbuffer:left_num()
    local batch_num = ringbuffer.batch_num
    local x = left_num / batch_num
    if (x - x % 1) > self.timer_num then
        return true
    end
    return false
end
```
check _need_timer where to create a timer before _flush_buffer function:
```
-        if not self.flushing and (ringbuffer:need_send() or is_exiting()) then
+        if not self.flushing and (_need_timer(self) or is_exiting()) then
             _flush_buffer(self)
```
At flush_buffer, when create timer success, add the timer_num by 1.
```
_flush_buffer = function (self)
    local ok, err = timer_at(0, _flush, self)
    if not ok then
        ngx_log(ERR, "failed to create timer at _flush_buffer, err: ", err)
        return
    end
+  self.timer_num = self.timer_num + 1
end
```
At the _flush function, minus 1.
```
local function _flush(premature, self)
+  self.timer_num = self.timer_num - 1
    if not _flush_lock(self) then
        if debug then
            ngx_log(DEBUG, "previous flush not finished")
        end
   ...
end
```
I test this fix, now it works well. But when sending faster, the buffer is overflow. The flushing lock between the timers lead to the low performance. Can we implement a lock free ringbuffer?

**Comment by doujiang24** [comment]
@chenyoufu Your fix have an problem: pending timer may turn to running fail, like exceeding the max running timer, so we have to implement a lock just like the flush_lock.

Because we have to keep the message order in the same topic-partition, we only have one thread to do the sending thing in the master branch now, but we can sending concurrency based on topic-partition, you can see the optimize in the concurrency branch :)

**Comment by chenyoufu** [comment]
@doujiang24 I am very sorry that I lose sight of the flush timer function running fail. I can not think a solution how to implement a lock just like the flush_lock. 
1. The pending_lock setting inside the timer _flush like flush_lock. 
2. The pending_lock setting outside the timer _flush, when can it be released? If released inside at flush timer, the timer running fail problem exists.
Could you give some hints?
Thanks.

**Comment by doujiang24** [comment]
@chenyoufu Sorry, I don't think we can optimize the lock now.
I think we need the `timer zone` in the ngx_lua core to handle this, like:
```config
lua_max_running_timers 10 kafka;
```
```lua
ngx.timer.at("kafka", func, ...)
```

for now, we can simply increase the max pending timer number.
There have only a very little time for a timer from pending to running, so not a very big number can handle this, like 8192?

**Comment by chenyoufu** [comment]
@doujiang24 now ngx_lua support timer zone?

**Comment by chenyoufu** [comment]
@doujiang24 thanks, In the near future, hope to be able to support  the  ```timer zone``` feature  in the ngx_lua core.

**Comment by gemelen** [comment]
Hi guys. We bumped into this too, so question is - do you had chance to check workaround with enlarging of timer's limits?

**Comment by doujiang24** [comment]
@gemelen We can use a larger `lua_max_pending_timers` for now, and it should be safe enough like `lua_max_pending_timers 40960` or larger :)
Finally, we will implement a new api `ngx.timer.every(interval, callback, ...)` and use it for cron timer, then we can add a lock for trigger pending timer, then it will be solved:)

**Comment by gemelen** [comment]
Ok, glad to hear this.
We tried this setting up to 8k, but it's still only a workaround.

**Comment by tokers** [comment]
@doujiang24 
Does this problem still exist?

**Comment by zhiquy** [comment]
i hava the problem too。a timer is send a batch_num message then exit，can i  make a loop to send more then one batch messages  in function _flush

**Comment by doujiang24** [comment]
@zhiquy @tokers 

there already has a PR: https://github.com/doujiang24/lua-resty-kafka/pull/73
but we need to improve it as I commented in the PR.

**Comment by doujiang24** [comment]
https://github.com/doujiang24/lua-resty-kafka/pull/83
