### ISSUE TITLE
async producer fails when first kafka instance in the list is down

### ISSUE THREAD

**Issue by pzhuk** [doujiang24/lua-resty-kafka#24]
I am using async kafka producer in our lua code, and we recently got situation than one of the kafka machines when down. Unfortunately, async client was continiously failing in this case, and I guess it was metadata request failing

The way we configure a kafka cluster in our lua config:

```
local config = {
  ["kafka"]={
    { host = "down", port = 9092 },
    { host = "foo", port = 9092 },
    { host = "bar", port = 9092 },
  },
}
```
Host 'down' obviously went down during incident. Others were up. All hosts are configured by IP addresses, not the hostnames

The way we use async producer:

```
      ....
local function send_messages_to_kafka(messages)
        local error_handle = function (topic, partition_id, queue, index, err, retryable)
          ngx.log(ngx.ERR, "failed to send to kafka: " .. err)
        end

        local producer_kafka, err = kafkaproducer:new(config.kafka, { producer_type = "async", refresh_interval = 5000, error_handle = error_handle })
        .....
```

And the result we observed in logs:
```

2016/04/24 12:04:06 [error] 22322#0: lua tcp socket connect timed out, context: ngx.timer, client: some.client.ip.here, server: 0.0.0.0:80
2016/04/24 12:04:06 [error] 22322#0: [lua] dataeye_logging_helper.lua:12: failed to send to kafka: timeout, context: ngx.timer, client: some.client.ip.here, server: 0.0.0.0:80

```

So my question here - is there any good  workaround for this problem? I can't really understand from the resty-kafka code if it performs fallback across multiple kafka instances

**Comment by doujiang24** [comment]
@pzhuk One thing need to confirm: the `failed to send` error log only exists for a little time after some broker down. If yes, then it is reasonable.
for the first error log `tcp socket connect timed out`: because we have to fetch the metadata from the kafka broker (yes always from the first one)
the second error log `failed to send`:  message will passed to error_handle after the `max_retry`, there have a time for the kafka to move one partition from the down broker to the alive ones:)

**Comment by vascop** [comment]
@doujiang24 I'm having the same problem, and can confirm it happens both with sync and async configurations. Whenever the first broker in the list is down there's no fallback to the other ones.

**Comment by doujiang24** [comment]
@vascop Actually the fallback is done in Kafka server, the resty-kafka only need to fetch metadata from the kafka server (if the first done, try the second one)
So, can you confirm:
1. does the resty-kafka tried the second broker?
2. fetch the metadata by some other shell tool to check if the kafka server removed the down broker ?

**Comment by vascop** [comment]
Actually I jumped the gun on this issue. I had deleted a previously created topic and forgot to set it up with replication on the second try, hence kafka wasn't doing the fallback. Sorry and thanks for your work with this!

**Comment by doujiang24** [comment]
consider resolved :)
