### ISSUE TITLE
send bytes to kafka throws an error

### ISSUE THREAD

**Issue by IvyTang** [doujiang24/lua-resty-kafka#25]
I'm try to send byte array to kafka.
`local ok, err = bp:send("m5", key, msg_bytes)`
and  msg_bytes is byte table.
But there throws an error.
`/lua-resty-kafka-master/lib/resty/kafka/request.lua:158: invalid value (table) at index 6 in table for 'concat'`

Then i checked the request.lua ,and i found 
```

    local req = {
        -- MagicByte
        str_int8(0),
        -- XX hard code no Compression
        str_int8(0),
        str_int32(key_len),
        key,
        str_int32(len),
        msg,
    }

    local str = concat(req)
```

Seems i can't send bytes to kafka,because  the client needs to concat the key and the message.

Is there any way i can send the bytes to kakfa directly , not encoding them with Base64?

**Comment by doujiang24** [comment]
@IvyTang you can simply send a string
You can simply concat your byte table to a string: `local str = table.concat(msg_bytes)`
