### ISSUE TITLE
no resolver defined to resolve "localhost"

### ISSUE THREAD

**Issue by midoks** [doujiang24/lua-resty-kafka#36]
return:
brokers: [{"host":"localhost","port":9092}]; partitions: {"0":{"id":0,"errcode":0,"replicas":[1],"isr":[1],"leader":1},"1":{"id":1,"errcode":0,"replicas":[1],"isr":[1],"leader":1},"errcode":0,"num":2}
send err1:no resolver defined to resolve "localhost"

code:

local cjson = require "cjson"
local client = require "resty.kafka.client"
local producer = require "resty.kafka.producer"

local broker_list = {
    --{ host = "192.168.1.1", port = 9092 },
    { host = "127.0.0.1", port = 9092 }
}

local key = "key"
local message = "halo world"

-- usually we do not use this library directly
local cli = client:new(broker_list)
local brokers, partitions = cli:fetch_metadata("test")
if not brokers then
    ngx.say("fetch_metadata failed, err:", partitions)
end
ngx.say("brokers: ", cjson.encode(brokers), "; partitions: ", cjson.encode(partitions))

-- sync producer_type
local p = producer:new(broker_list)

local offset, err = p:send("test", key, message)
if not offset then
    ngx.say("send err1:", err)
    return
end
ngx.say("send success, offset: ", tonumber(offset))

How can I solve it？

**Comment by doujiang24** [comment]
@midoks 
https://github.com/doujiang24/lua-resty-kafka/issues/5
