### ISSUE TITLE
lua-resty-kafka require error

### ISSUE THREAD

**Issue by sakmon** [doujiang24/lua-resty-kafka#37]
when i require resty.kafka.producer , the error log show:

2016/08/26 14:10:54 [error] 11222#0: *284 lua entry thread aborted: runtime error: error loading module 'resty.kafka.response' from file '/usr/local/lib/lua/resty/kafka/response.lua':
	/usr/local/lib/lua/resty/kafka/response.lua:76: malformed number near '4294967296LL'
stack traceback:
coroutine 0:
	[C]: ?
	[C]: in function 'require'
	/usr/local/lib/lua/resty/kafka/producer.lua:4: in main chunk
	[C]: in function 'require'

**Comment by doujiang24** [comment]
@sakmon we only support LuaJIT now, better to check your OpenResty have enable LuaJIT.

**Comment by sakmon** [comment]
@doujiang24
