### ISSUE TITLE
ngx.req.get_body_data() 通过kafka发送中文乱码

### ISSUE THREAD

**Issue by xj198806** [doujiang24/lua-resty-kafka#43]
local producer = require "resty.kafka.producer"

local broker_list = {  
		{ host = "10.7.13.112", port = 9092 },  
		{ host = "10.7.13.114", port = 9092 },
		{ host = "10.7.13.115", port = 9092 },	
	}
ngx.req.read_body()
local post = ngx.req.get_body_data()
local bp = producer:new(broker_list, { producer_type = "async" })  	  
if post then
	local ok, err = bp:send("footPrint_eventlog", nil,post) 
	if not ok then  
		ngx.log(ngx.ERR, "kafka send err:", err)  
		return  
	end
	ngx.say("{\"code\":200,\"description\":\"ok\"}")
else
	ngx.say("{\"code\":400,\"description\":\"no content\"}")
end

kafka 发送post数据成功 接受到消息 中文有乱码 post通过ngx.log 输出文件没有乱码 求问大神什么原因

**Comment by xj198806** [comment]
貌似是我curl 请求编码有点不对

**Comment by doujiang24** [comment]
@xj198806 So, I'm closing it
