### ISSUE TITLE
buffered messages send to kafka err: MessageSizeTooLarge

### ISSUE THREAD

**Issue by centralman** [doujiang24/lua-resty-kafka#45]
2016/12/22 22:32:33 [error] 13413#0: *378703 [lua] producer.lua:258: buffered messages send to kafka err: MessageSizeTooLarge, retryable: false, topic: ns-source-wimonitor, partition_id: 2, length: 111, context: ngx.timer, client: 120.237.52.234, server: 0.0.0.0:443

I have got a error from error.log. should i increase the message size? and what should i do?

**Comment by doujiang24** [comment]
@centralman Maybe you shoud config `max.message.bytes`  on the kafka side?
http://kafka.apache.org/documentation.html#producerconfigs

**Comment by centralman** [comment]
Thanks a lot. I'm a beginner to kafka.
