### ISSUE TITLE
I would like to ask if the lua-resty-kafka supports the transfer file

### ISSUE THREAD

**Issue by 2015java** [doujiang24/lua-resty-kafka#49]
I would like to ask if the lua-resty-kafka supports the transfer file

**Comment by doujiang24** [comment]
@2015java Yes, messages can be any bytes.

**Comment by BlackGhostKing** [comment]
but java client get data  is string

**Comment by 2015java** [comment]
@BlackGhostKing ,Java client can convert a string to a file from kafka
