### ISSUE TITLE
is there any plan to support ssl?

### ISSUE THREAD

**Issue by laoshancun** [doujiang24/lua-resty-kafka#56]
is there any plan to support ssl?

**Comment by xlingit** [comment]
@laoshancun ,ssl problem solved yet?

**Comment by laoshancun** [comment]
Not yet, but I changed my plan.

**Comment by assada** [comment]
any update?

**Comment by assada** [comment]
@doujiang24 Is there any plan to add this feature?

**Comment by doujiang24** [comment]
> @doujiang24 Is there any plan to add this feature?

no plan from my side yet, patches welcome :)

**Comment by murillopaula** [comment]
@doujiang24 we would love to have support for ssl or sasl. I see that there was an effort to [add support for sasl_plain](https://github.com/doujiang24/lua-resty-kafka/pull/63) but it was closed. Do you remember why it was closed? What's left to complete that patch? Any potential challenges that you foresee?

**Comment by doujiang24** [comment]
@murillopaula it's closed by the original author, PR welcome :)
and we have enabled the Travis ci now,  please remember to add related test cases for it :)

**Comment by jeremyjpj0916** [comment]
+1, would love to see TLS support in this plugin with Kafka. I need it for a logging effort.

**Comment by doujiang24** [comment]
@jeremyjpj0916 yeah, you are right, PR welcome, thanks :)

**Comment by jeremyjpj0916** [comment]
Technically this issue can be closed. This lib. Now supports ssl connections.

**Comment by doujiang24** [comment]
@jeremyjpj0916 Thanks, closing it.
