### ISSUE TITLE
send err:not foundd topic

### ISSUE THREAD

**Issue by lilbrianxp** [doujiang24/lua-resty-kafka#6]
Hi,

Not sure why I'm getting this error and the topic do exist. I also tested it through client python with the same topic and that worked.

....
....

local broker_list = {
             { host = "127.0.0.1", port = 9092 },
         }

 		local key = "key1"
         local message = "hello world"
         local p = producer:new(broker_list)

         local offset, err = p:send("test", key,message)
         if not offset then
             ngx.say("send err:", err)
             return
         end
         ngx.say("send success, offset: ", tostring(offset))

Using:
Openresty 1.7.2.1
kafka server 2.10-0.8.2.0

Also, I tested on 0.8.1 and 0.8.1.1
Thanks,

**Comment by doujiang24** [comment]
I'm not sure if this is your situation:

1. newly kafka server, topic `test` not created manually
2. first send error : not foundd topic, but then will be all right

cause a non-existent topic will automatically create in default kafka config
if this matches your situation, you are recommended to create topic manually

python works fine, maybe it will auto retry when not found topic

**Comment by afsheenb** [comment]
I was getting the same error for unrelated reasons, just now I've solved it. It may be the same issue as @lilbrianxp , hard to say.

The full error message I received is: 

2015/04/29 19:43:17 [error] 1928#0: [lua] producer.lua:254: buffered messages send to kafka err: not foundd topic, retryable: true, topic: test, partition_id: -1, length: 1, context: ngx.timer

That -1 for partition id is the problem. My topic has 500 partitions, and I think fetch_metadata() isn't parsing the list of partitions correctly. 

I was able to "fix" this (well, at least well enough to identify the issue) by hardcoding my # of partitions into producer.lua:

    return self.partitioner(key, "500", self.correlation_id)

...and magically all works as expected now!

Here's what zookeeper displays when i run get /brokers/topics for my two testing topics, one that the current code in master can send to, and one that throws an error unless I hardcode my # of partitions.

Works fine with no hacks:

[zk: localhost:2181(CONNECTED) 4] get /brokers/topics/test
{"version":1,"partitions":{"0":[0]}}
cZxid = 0x11803
ctime = Wed Apr 29 17:29:52 UTC 2015
mZxid = 0x11803
mtime = Wed Apr 29 17:29:52 UTC 2015
pZxid = 0x11806
cversion = 1
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 36
numChildren = 1

Works only with hardcoded value:

[zk: localhost:2181(CONNECTED) 3] get /brokers/topics/test500
{"version":1,"partitions":{"205":[0],"45":[0],"98":[0],"113":[0],"34":[0],"381":[0],"455":[0],"67":[0],"388":[0],"310":[0],"169":[0],"444":[0],"120":[0],"193":[0],"302":[0],"153":[0],"335":[0],"93":[0],"158":[0],"458":[0],"142":[0],"182":[0],"147":[0],"436":[0],"12":[0],"223":[0],"66":[0],"216":[0],"89":[0],"51":[0],"124":[0],"84":[0],"8":[0],"400":[0],"73":[0],"411":[0],"307":[0],"276":[0],"164":[0],"170":[0],"425":[0],"78":[0],"447":[0],"461":[0],"324":[0],"332":[0],"175":[0],"19":[0],"313":[0],"362":[0],"265":[0],"100":[0],"23":[0],"433":[0],"62":[0],"321":[0],"135":[0],"128":[0],"4":[0],"121":[0],"343":[0],"404":[0],"88":[0],"421":[0],"450":[0],"77":[0],"415":[0],"40":[0],"318":[0],"378":[0],"418":[0],"373":[0],"110":[0],"469":[0],"284":[0],"475":[0],"295":[0],"320":[0],"481":[0],"15":[0],"269":[0],"486":[0],"11":[0],"104":[0],"396":[0],"90":[0],"9":[0],"141":[0],"139":[0],"181":[0],"132":[0],"201":[0],"44":[0],"236":[0],"385":[0],"33":[0],"117":[0],"273":[0],"497":[0],"197":[0],"492":[0],"346":[0],"280":[0],"287":[0],"454":[0],"466":[0],"351":[0],"407":[0],"291":[0],"262":[0],"470":[0],"298":[0],"186":[0],"227":[0],"250":[0],"399":[0],"392":[0],"22":[0],"56":[0],"329":[0],"55":[0],"212":[0],"393":[0],"163":[0],"26":[0],"224":[0],"303":[0],"134":[0],"244":[0],"50":[0],"460":[0],"123":[0],"390":[0],"174":[0],"410":[0],"361":[0],"382":[0],"429":[0],"37":[0],"68":[0],"242":[0],"166":[0],"61":[0],"107":[0],"491":[0],"356":[0],"217":[0],"336":[0],"328":[0],"13":[0],"46":[0],"206":[0],"255":[0],"325":[0],"296":[0],"99":[0],"437":[0],"177":[0],"441":[0],"24":[0],"253":[0],"209":[0],"459":[0],"155":[0],"94":[0],"448":[0],"83":[0],"414":[0],"35":[0],"314":[0],"233":[0],"306":[0],"16":[0],"379":[0],"192":[0],"495":[0],"79":[0],"398":[0],"426":[0],"279":[0],"341":[0],"152":[0],"231":[0],"367":[0],"5":[0],"350":[0],"480":[0],"103":[0],"112":[0],"72":[0],"268":[0],"387":[0],"10":[0],"274":[0],"330":[0],"199":[0],"159":[0],"59":[0],"353":[0],"144":[0],"87":[0],"237":[0],"263":[0],"256":[0],"340":[0],"317":[0],"196":[0],"375":[0],"48":[0],"281":[0],"403":[0],"476":[0],"422":[0],"21":[0],"116":[0],"484":[0],"498":[0],"76":[0],"419":[0],"228":[0],"372":[0],"270":[0],"347":[0],"138":[0],"54":[0],"188":[0],"473":[0],"408":[0],"43":[0],"148":[0],"127":[0],"339":[0],"487":[0],"65":[0],"71":[0],"57":[0],"213":[0],"285":[0],"292":[0],"108":[0],"259":[0],"202":[0],"248":[0],"479":[0],"364":[0],"32":[0],"185":[0],"445":[0],"472":[0],"297":[0],"80":[0],"434":[0],"219":[0],"428":[0],"360":[0],"106":[0],"234":[0],"252":[0],"137":[0],"431":[0],"82":[0],"49":[0],"6":[0],"413":[0],"126":[0],"383":[0],"241":[0],"36":[0],"386":[0],"1":[0],"490":[0],"300":[0],"348":[0],"337":[0],"39":[0],"286":[0],"289":[0],"140":[0],"409":[0],"173":[0],"17":[0],"180":[0],"267":[0],"394":[0],"290":[0],"221":[0],"25":[0],"60":[0],"397":[0],"208":[0],"14":[0],"133":[0],"47":[0],"391":[0],"122":[0],"230":[0],"309":[0],"111":[0],"102":[0],"31":[0],"96":[0],"69":[0],"162":[0],"463":[0],"442":[0],"344":[0],"278":[0],"191":[0],"494":[0],"456":[0],"151":[0],"245":[0],"95":[0],"190":[0],"322":[0],"405":[0],"58":[0],"368":[0],"145":[0],"477":[0],"315":[0],"184":[0],"483":[0],"264":[0],"257":[0],"439":[0],"64":[0],"225":[0],"214":[0],"53":[0],"389":[0],"203":[0],"249":[0],"42":[0],"75":[0],"499":[0],"246":[0],"115":[0],"195":[0],"467":[0],"275":[0],"376":[0],"156":[0],"308":[0],"452":[0],"293":[0],"109":[0],"189":[0],"0":[0],"149":[0],"354":[0],"20":[0],"326":[0],"178":[0],"357":[0],"430":[0],"260":[0],"365":[0],"311":[0],"488":[0],"27":[0],"70":[0],"210":[0],"266":[0],"2":[0],"402":[0],"86":[0],"38":[0],"238":[0],"371":[0],"81":[0],"167":[0],"423":[0],"271":[0],"304":[0],"333":[0],"416":[0],"282":[0],"493":[0],"198":[0],"277":[0],"283":[0],"338":[0],"294":[0],"474":[0],"482":[0],"160":[0],"118":[0],"187":[0],"395":[0],"171":[0],"345":[0],"165":[0],"443":[0],"235":[0],"374":[0],"92":[0],"462":[0],"446":[0],"412":[0],"125":[0],"18":[0],"489":[0],"363":[0],"427":[0],"261":[0],"438":[0],"464":[0],"101":[0],"247":[0],"319":[0],"258":[0],"194":[0],"154":[0],"215":[0],"220":[0],"183":[0],"30":[0],"7":[0],"352":[0],"143":[0],"97":[0],"331":[0],"130":[0],"179":[0],"218":[0],"435":[0],"114":[0],"222":[0],"432":[0],"272":[0],"496":[0],"251":[0],"478":[0],"457":[0],"359":[0],"207":[0],"288":[0],"129":[0],"29":[0],"471":[0],"41":[0],"299":[0],"485":[0],"240":[0],"384":[0],"168":[0],"105":[0],"468":[0],"63":[0],"254":[0],"211":[0],"232":[0],"150":[0],"204":[0],"3":[0],"369":[0],"342":[0],"420":[0],"323":[0],"74":[0],"243":[0],"226":[0],"366":[0],"305":[0],"91":[0],"453":[0],"52":[0],"85":[0],"172":[0],"406":[0],"451":[0],"355":[0],"316":[0],"380":[0],"440":[0],"449":[0],"377":[0],"424":[0],"334":[0],"131":[0],"401":[0],"229":[0],"465":[0],"200":[0],"327":[0],"349":[0],"370":[0],"28":[0],"301":[0],"119":[0],"161":[0],"417":[0],"136":[0],"157":[0],"146":[0],"176":[0],"358":[0],"239":[0],"312":[0]}}
cZxid = 0x11832
ctime = Wed Apr 29 19:09:19 UTC 2015
mZxid = 0x11832
mtime = Wed Apr 29 19:09:19 UTC 2015
pZxid = 0x11832
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 4918
numChildren = 0


Please let me know if you need any more information to help troubleshoot this.

**Comment by doujiang24** [comment]
Sorry for the late and thank you for the information

It works well on my side with 500 partitions

```lua
local producer = require "resty.kafka.producer"

local broker_list = {
    { host = "127.0.0.1", port = 9092 },
}

local key = "key"
local message = "halo world"

local p = producer:new(broker_list, { producer_type = "async", flush_time = 10000 })
ngx.sleep(0.1) -- will have an immediately flush by timer_flush

local ok, err = p:send("test500", key, message)
if not ok then
    ngx.say("send err:", err)
    return
end
ngx.say("send ok:", ok)

p:flush()
local offset0 = p:offset()

for i = 1, 50000 do
    local ok, err = p:send("test500", key, message)
    if not ok then
        ngx.say("send err:", err)
        return
    end
    p:flush()

end
local offset1 = p:offset()

ngx.say("send num:", tonumber(offset1 - offset0))
```
works fine:
```
send ok:true
send num:50000
```

and your 'fix' looks really magic for me.
so could you test this code on your side?

```lua
                local cjson = require "cjson"
                local client = require "resty.kafka.client"

                local broker_list = {
                    { host = "127.0.0.1", port = 9092 },
                }

                -- usually we do not use this library directly
                local cli = client:new(broker_list)
                local brokers, partitions = cli:fetch_metadata("test")
                if not brokers then
                    ngx.say("fetch_metadata failed, err:", partitions)
                end
                ngx.say("brokers: ", cjson.encode(brokers), "; partitions: ", cjson.encode(partitions))
```

thanks :)

**Comment by doujiang24** [comment]
@afsheenb 

could you add some debug log? 
Or if it's possible for me to get you environment? I can not reproduce on my side

```lua
local cjson = require "cjson"
local function choose_partition(self, topic, key)
    local brokers, partitions = self.client:fetch_metadata(topic)
    if not brokers then
        return nil, partitions
    end
    ngx.log(ngx.ERR, cjson.encode(partitions))
    return self.partitioner(key, partitions.num, self.correlation_id)
end
```

**Comment by afsheenb** [comment]
So it looks like pulling from master and trying again 'fixed' my issue! I'll delete my comment, it's no longer relevant and I think may be confusing for others.

**Comment by sunchenxian** [comment]
Hi lilbrianxp:
     I have the same problem like "not foundd topic",but the topic has been created before, how to resolve it, thanks. 

Using:
Openresty 1.7.10.1
kafka server 2.10-0.8.2.1

**Comment by doujiang24** [comment]
@sunchenxian 
thanks for the report, are you using the master code?
if it is yes, could you try the debug code I list before, I can not reproducer the error on my side

**Comment by sunchenxian** [comment]
@doujiang24 
Hi, I have tried the following debug code:
     
      local cjson = require "cjson"
      local client = require "resty.kafka.client"
      local producer = require "resty.kafka.producer"

      local broker_list = {
            {host="127.0.0.1",port=9093},
      }

     local cli = client:new( broker_list )
     local brokers, partitions = cli:fetch_metadata( "test" )
     if not brokers then
           ngx.say( "fetch_metadata failed, err:", partitions )
     end
     ngx.say( "brokers: ", cjson.encode( brokers ), "; partitions: ", cjson.encode(  partitions ) )
     ngx.exit( 200 )

It prints debug message to me:
    
     brokers: [{"host":"localhost","port":9093},{"host":"localhost","port":9094},    {"host":"localhost","port":9095}]; partitions: {"0":{"id":0,"errcode":0,"replicas":[3,2,1],"isr":[3],"leader":3},"errcode":0,"num":1} 


if I run the following code, it print "not foundd topic", I have created the topic before.

     local cjson = require "cjson"
     local client = require "resty.kafka.client"
     local producer = require "resty.kafka.producer"

     local brokers = {
           {host="localhost",port=9093},
     }

     local message = "hello world"
     local p = producer:new( brokers, {producer_type="sync"} )
     local offset, err = p:send( "test", nil, message )

    if not offset then
          ngx.say( "err:" .. err )
    end

    ngx.exit(200)

waiting for your reply.

**Comment by doujiang24** [comment]
@sunchenxian 
seems like nginx can not resolve `localhost` on your side, that the producer can not fetch the metadata from broker
Do you see any error info in `/path/to/nginx/log/error.log` ?

**Comment by sunchenxian** [comment]
@doujiang24 
Hi,  there are some errors in  error log file：
       
         2015/06/09 10:08:18 [error] 31350#0: [lua] client.lua:150: _fetch_metadata(): all brokers failed in fetch topic metadata, context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9100
         2015/06/09 10:08:18 [error] 31350#0: [lua] client.lua:150: _fetch_metadata(): all brokers failed in fetch topic metadata, context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9100
         2015/06/09 10:08:18 [error] 31350#0: [lua] producer.lua:255: buffered messages send to kafka err: not foundd topic, retryable: true, topic: test, partition_id: -1, length: 1, context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9100

I will try a domain instead of localhost to verify your guess.

**Comment by sunchenxian** [comment]
Hi doujiang24:
      I have verified your guess, It retured right information to me when I set host.name to "127.0.0.1" in all broker config files, but  I don't know why does the kafka server  unrecognize “localhost”，I have setted localhost in file /etc/hosts.
      thank you for all your replies.

**Comment by skadilover** [comment]
我发现如果没有在nginx中填写正确的reslover也会导致no foundd topic

                resolver  10.10.114.140 //如果没有这一行
                local broker_list = {
                    { host = "xxx.xxx.xxx.xxxx", port = 9092 },
                }

**Comment by chenyoufu** [comment]
I bypass the resolver Instruction and the kafka setting.Now kafka return the IP address or the Hostname both work.
```lua
local hostname2ip = {
  ["kafka-node0"] = "192.168.10.34",
  ["kafka-node1"] = "192.168.10.35",
  ["kafka-node2"] = "192.168.10.36"
}

-- sync producer_type
local p = producer:new(broker_list)
p.client:fetch_metadata('ngx-test')
for k, v in pairs(p.client.brokers) do
  if hostname2ip[v.host] then
    p.client.brokers[k].host = hostname2ip[v.host]
  end
end
```

**Comment by doujiang24** [comment]
@chenyoufu It's really not a good idea. You'd better change the `host.name` in your kafka config or use your local dns.

**Comment by doujiang24** [comment]
@sunchenxian Actually, it's not kafka server unrecognize “localhost”, it's nginx unrecognize `localhost`, because do not use the config in `/etc/hosts`.

**Comment by skadilover** [comment]
是的

**Comment by doujiang24** [comment]
Consider it resolved.

**Comment by liuyanagit** [comment]
> 我发现如果没有在nginx中填写正确的reslover也会导致no foundd topic
> 
> ```
>             resolver  10.10.114.140 //如果没有这一行
>             local broker_list = {
>                 { host = "xxx.xxx.xxx.xxxx", port = 9092 },
>             }
> ```

请问resolver后面这个ip是指的你本机ip？我现在遇到了同样的问题。如果broker_list中配置了域名，就会出现not found topic。如果broker_list中配置了域名解析后的ip就能成功写入。请问你是怎么解决得呢？
![image](https://user-images.githubusercontent.com/54139950/66974259-1f8ff200-f0cd-11e9-801b-284e438fedbf.png)

**Comment by liuyanagit** [comment]
> 是的，我也发现时nginx不能发现域名

请问你是怎么解决得呢？由于域名解析后的ip是不固定的，所以我们不能写死ip，而只能用域名。

**Comment by liuyanagit** [comment]
我将resolver 1.1.1.1（dns-ip）;加入到nginx conf中就可以了
太感谢大家的回复了
