### ISSUE TITLE
即使是在异常情况下，为什么producer：send返回的都是true呢

### ISSUE THREAD

**Issue by wangzili064** [doujiang24/lua-resty-kafka#75]
![image](https://user-images.githubusercontent.com/49544582/56015496-cf099780-5d2b-11e9-9fe1-5a857568e8c5.png)

**Comment by wangzili064** [comment]
local bp = producer:new(broker_list, { producer_type = "async" })
            local ok, err = bp:send("jb_unify_log_info", nil, message)
            ngx.log(ngx.ERR, "kafka send err message---err:", err)
            ngx.log(ngx.ERR, "kafka send err message---ok:", ok)
            ngx.log(ngx.ERR, "kafka send err message:", type(ok))
            if not ok then
                ngx.log(ngx.ERR, "kafka send err message:", message)
                return
            else

**Comment by wangzili064** [comment]
![image](https://user-images.githubusercontent.com/49544582/56015670-6a9b0800-5d2c-11e9-9e51-27c7d3c3315c.png)

**Comment by xiaooloong** [comment]
`producer_type = 'async'`
异步发送的原因吧。异步模式发送只是把消息添加到队列就返回成功了。然后定时或者队列满了才批量发送的。那个时候已经脱离了当前的请求了。

**Comment by wangzili064** [comment]
> `producer_type = 'async'`
> 异步发送的原因吧。异步模式发送只是把消息添加到队列就返回成功了。然后定时或者队列满了才批量发送的。那个时候已经脱离了当前的请求了。

嗯，应该是，多谢了

**Comment by doujiang24** [comment]
@wangzili064 是的，异步模式下，只有 buffer 满了才会返回错误的
具体原因正如 @xiaooloong 说的那样

**Comment by wangzili064** [comment]
> @wangzili064 是的，异步模式下，只有 buffer 满了才会返回错误的
> 具体原因正如 @xiaooloong 说的那样

那怎么设置成同步呢，是不是不支持

**Comment by doujiang24** [comment]
@wangzili064 请仔细看文档：https://github.com/doujiang24/lua-resty-kafka#restykafkaproducer，`producer_type`.

**Comment by wangzili064** [comment]
> @wangzili064 请仔细看文档：[https://github.com/doujiang24/lua-resty-kafka#restykafkaproducer，`producer_type`](https://github.com/doujiang24/lua-resty-kafka#restykafkaproducer%EF%BC%8C%60producer_type%60).
sorry，已了解，多谢您

**Comment by wangzili064** [comment]
> > @wangzili064 请仔细看文档：[https://github.com/doujiang24/lua-resty-kafka#restykafkaproducer，`producer_type`](https://github.com/doujiang24/lua-resty-kafka#restykafkaproducer%EF%BC%8C%60producer_type%60).
> > sorry，已了解，多谢您

还是想打扰一下，看了文档，觉得异步的话，我还是没办法获取回调信息呢
