### ISSUE TITLE
Create a tag with latest commit

### ISSUE THREAD

**Issue by starsz** [doujiang24/lua-resty-kafka#85]
Hello, doujiang. I am so glad to hear that you had fixed the many timers problem. 
Why not bump a new version ?

**Comment by doujiang24** [comment]
@starsz thanks for your remind, just created the `v0.08` release.

**Comment by starsz** [comment]
@doujiang24 Sorry to disturb, you had forgotten to upload to luarocks.

**Comment by doujiang24** [comment]
https://luarocks.org/modules/doujiang24/lua-resty-kafka/0.08-0
@starsz thanks for your remind :)
