### ISSUE TITLE
producer.lua:354: attempt to call upvalue 'timer_every' (a nil value)

### ISSUE THREAD

**Issue by Simon0910** [doujiang24/lua-resty-kafka#86]
2020/02/22 06:23:18 [error] 2878#0: *1 lua entry thread aborted: runtime error: /usr/eshop/hello/lualib/resty/kafka/producer.lua:354: attempt to call upvalue 'timer_every' (a nil value)
stack traceback:
coroutine 0:
        /usr/eshop/hello/lualib/resty/kafka/producer.lua: in function 'new'

**Comment by doujiang24** [comment]
seems you are using an old openresty, we now rely on the `ngx.timer.every` API.
https://github.com/openresty/lua-nginx-module/#ngxtimerevery

can you show your openresty version by using `nginx -V`?

**Comment by Simon0910** [comment]
[root@eshop01 logs]# /usr/servers/nginx/sbin/nginx -V
nginx version: openresty/1.7.7.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) 
TLS SNI support enabled
configure arguments: --prefix=/usr/servers/nginx --with-cc-opt='-I/usr/servers/ngx_openresty-1.7.7.2/build/luajit-root/usr/servers/luajit/include/luajit-2.1 -O2' --add-module=../ngx_devel_kit-0.2.19 --add-module=../echo-nginx-module-0.57 --add-module=../xss-nginx-module-0.04 --add-module=../ngx_coolkit-0.2rc2 --add-module=../set-misc-nginx-module-0.28 --add-module=../form-input-nginx-module-0.10 --add-module=../encrypted-session-nginx-module-0.03 --add-module=../srcache-nginx-module-0.28 --add-module=../ngx_lua-0.9.14 --add-module=../ngx_lua_upstream-0.02 --add-module=../headers-more-nginx-module-0.25 --add-module=../array-var-nginx-module-0.03 --add-module=../memc-nginx-module-0.15 --add-module=../redis2-nginx-module-0.11 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.13 --add-module=../rds-csv-nginx-module-0.05 --with-ld-opt='-Wl,-rpath,/usr/servers/luajit/lib -L/usr/servers/ngx_openresty-1.7.7.2/build/luajit-root/usr/servers/luajit/lib' --with-http_realip_module --with-pcre --add-module=/usr/servers/ngx_openresty-1.7.7.2/bundle/ngx_cache_purge-2.3 --add-module=/usr/servers/ngx_openresty-1.7.7.2/bundle/nginx_upstream_check_module-0.3.0 --with-http_ssl_module

**Comment by doujiang24** [comment]
the current ngx_lua module you are using is too old, `--add-module=../ngx_lua-0.9.14` vs `This API was first introduced in the v0.10.9 release`.
you are recommended to use the latest release.

https://github.com/openresty/lua-nginx-module/#ngxtimerevery

**Comment by doujiang24** [comment]
https://github.com/openresty/lua-nginx-module/releases/tag/v0.10.15
you can try this release.

**Comment by Simon0910** [comment]
Thank you in the end I used openresty-1.15.8.2.tar.gz to solve

**Comment by Simon0910** [comment]
Thank you in the end I used openresty-1.15.8.2.tar.gz to solve
