### ISSUE TITLE
每次访问都报这个错？

### ISSUE THREAD

**Issue by King2Jack** [doujiang24/lua-resty-kafka#89]
resty/kafka/producer.lua:354: attempt to call upvalue 'timer_every' (a nil value)
stack traceback:
coroutine 0:
	/usr/hello/lualib/resty/kafka/producer.lua: in function 'new'

**Comment by doujiang24** [comment]
@King2Jack you need the newer openresty release, just like this issue.
https://github.com/doujiang24/lua-resty-kafka/issues/88#issuecomment-600151531
