### ISSUE TITLE
nginx restart， reload, stop start会丢失数据吗？

### ISSUE THREAD

**Issue by sugue** [doujiang24/lua-resty-kafka#92]
代码是通过定时器把消息定时发送的， 在做restart, reload, stop start三种操作的时候， 会不会定时器没来的及启动， 然后没有发送出去的buf就丢失了？

**Comment by doujiang24** [comment]
`-HUP` 和 `-QUIT` 这种优雅退出是没问题的，普通的 kill，尤其是 kill -9 这种，系统不会给应用程序善后处理机会的

这个问题建议去 OpenResty 官方论坛讨论：https://forum.openresty.us/
